//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET应用开发平台是一套免费的快速开发工具，可以不受限制的用于各种商业开发之中，开发人员可以参考官方网站和博客园
//等专业网站获取公开的技术资料，也可以向AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;
using System.Data;

namespace EAS.Explorer.Entities
{
   /// <summary>
    /// 实体对象 GroupModule(模块信息/分组)。
   /// </summary>
   [Serializable()]
   [Table("EAS_GROUP_MODULES"), Index]
   partial class NavigateModule : DataEntity<NavigateModule>
   {
       public NavigateModule()
       {
       }

       protected NavigateModule(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }

       #region O/R映射成员

       /// <summary>
       /// 模块Guid 。
       /// </summary>
       [Column("GUID", "模块Guid"), PrimaryKey]
       public string Guid
       {
           get
           {
               return this.GetValue<string>("GUID");
           }
           set
           {
               this["GUID"] = value;
           }
       }

       /// <summary>
       /// 模块名称 。
       /// </summary>
       [Column("NAME", "模块名称")]
       public string Name
       {
           get
           {
               return this.GetValue<string>("NAME");
           }
           set
           {
               this["NAME"] = value;
           }
       }

       /// <summary>
       /// 程序集 。
       /// </summary>
       [Column("ASSEMBLY", "程序集")]
       public string Assembly
       {
           get
           {
               return this.GetValue<string>("ASSEMBLY");
           }
           set
           {
               this["ASSEMBLY"] = value;
           }
       }

       /// <summary>
       /// 类型 。
       /// </summary>
       [Column("TYPE", "类型")]
       public string Type
       {
           get
           {
               return this.GetValue<string>("TYPE");
           }
           set
           {
               this["TYPE"] = value;
           }
       }

       /// <summary>
       /// 版本 。
       /// </summary>
       [Column("VERSION", "版本")]
       public string Version
       {
           get
           {
               return this.GetValue<string>("VERSION");
           }
           set
           {
               this["VERSION"] = value;
           }
       }

       /// <summary>
       /// 开发者 。
       /// </summary>
       [Column("DEVELOPER", "开发者")]
       public string Developer
       {
           get
           {
               return this.GetValue<string>("DEVELOPER");
           }
           set
           {
               this["DEVELOPER"] = value;
           }
       }

       /// <summary>
       /// 说明 。
       /// </summary>
       [Column("DESCRIPTION", "说明")]
       public string Description
       {
           get
           {
               return this.GetValue<string>("DESCRIPTION");
           }
           set
           {
               this["DESCRIPTION"] = value;
           }
       }

       /// <summary>
       /// Url 。
       /// </summary>
       [Column("URL", "Url")]
       public string Url
       {
           get
           {
               return this.GetValue<string>("URL");
           }
           set
           {
               this["URL"] = value;
           }
       }

       /// <summary>
       /// 排序码 。
       /// </summary>
       [Column("SORTCODE", "排序码")]
       public int SortCode
       {
           get
           {
               return this.GetValue<int>("SORTCODE");
           }
           set
           {
               this["SORTCODE"] = value;
           }
       }

       /// <summary>
       /// 模块包 。
       /// </summary>
       [Column("PACKAGE", "模块包")]
       public string Package
       {
           get
           {
               return this.GetValue<string>("PACKAGE");
           }
           set
           {
               this["PACKAGE"] = value;
           }
       }

       /// <summary>
       /// 图标 。
       /// </summary>
       [Column("ICON", "图标", DbType.Binary)]
       public byte[] Icon
       {
           get
           {
               return this.GetValue<byte[]>("ICON");
           }
           set
           {
               this["ICON"] = value;
           }
       }

       /// <summary>
       /// 更新时间 。
       /// </summary>
       [Column("LMTIME", "更新时间")]
       public DateTime LMTime
       {
           get
           {
               return this.GetValue<DateTime>("LMTIME");
           }
           set
           {
               this["LMTIME"] = value;
           }
       }

       /// <summary>
       /// 分组ID 。
       /// </summary>
       [Column("GROUPID", "分组ID")]
       public string GroupID
       {
           get
           {
               return this.GetValue<string>("GROUPID");
           }
           set
           {
               this["GROUPID"] = value;
           }
       }       

       /// <summary>
       /// 分组名称 。
       /// </summary>
       [Column("GROUPNAME", "分组名称")]
       public string GroupName
       {
           get
           {
               return this.GetValue<string>("GROUPNAME");
           }
           set
           {
               this["GROUPNAME"] = value;
           }
       }

       /// <summary>
       /// 属性 。
       /// </summary>
       [Column("ATTRIBUTES", "属性"), DataSize(10)]
       public int Attributes
       {
           get
           {
               return this.GetValue<int>("ATTRIBUTES");
           }
           set
           {
               this["ATTRIBUTES"] = value;
           }
       }
       
       #endregion
   }
}
