//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET应用开发平台是一套免费的快速开发工具，可以不受限制的用于各种商业开发之中，开发人员可以参考官方网站和博客园
//等专业网站获取公开的技术资料，也可以向AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace EAS.Explorer.Entities
{
    /// <summary>
    /// 实体对象 Organization(机构部门)。
    /// </summary>
    [Serializable()]
    [Table("EAS_ORGANIZATION", "机构部门"), Index]
    partial class Organization : DataEntity<Organization>
    {
        public Organization()
        {
        }

        protected Organization(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }

        #region O/R映射成员

        /// <summary>
        /// Guid 。
        /// </summary>
        [Column("GUID", "Guid"), DataSize(36), PrimaryKey]
        public string Guid
        {
            get
            {
                return this.GetValue<string>("GUID");
            }
            set
            {
                this["GUID"] = value;
            }
        }

        /// <summary>
        /// 上级机构 。
        /// </summary>
        [Column("PARENTID", "上级机构"), DataSize(36)]
        public string ParentID
        {
            get
            {
                return this.GetValue<string>("PARENTID");
            }
            set
            {
                this["PARENTID"] = value;
            }
        }

        /// <summary>
        /// 名称 。
        /// </summary>
        [Column("NAME", "名称"), DataSize(64)]
        public string Name
        {
            get
            {
                return this.GetValue<string>("NAME");
            }
            set
            {
                this["NAME"] = value;
            }
        }

        /// <summary>
        /// 地址 。
        /// </summary>
        [Column("ADDRESS", "地址"), DataSize(128)]
        public string Address
        {
            get
            {
                return this.GetValue<string>("ADDRESS");
            }
            set
            {
                this["ADDRESS"] = value;
            }
        }

        /// <summary>
        /// 联系人 。
        /// </summary>
        [Column("CONTACT", "联系人"), DataSize(64)]
        public string Contact
        {
            get
            {
                return this.GetValue<string>("CONTACT");
            }
            set
            {
                this["CONTACT"] = value;
            }
        }

        /// <summary>
        /// 电话 。
        /// </summary>
        [Column("TEL", "电话"), DataSize(64)]
        public string Tel
        {
            get
            {
                return this.GetValue<string>("TEL");
            }
            set
            {
                this["TEL"] = value;
            }
        }

        /// <summary>
        /// 传真 。
        /// </summary>
        [Column("FAX", "传真"), DataSize(64)]
        public string Fax
        {
            get
            {
                return this.GetValue<string>("FAX");
            }
            set
            {
                this["FAX"] = value;
            }
        }

        /// <summary>
        /// 邮件 。
        /// </summary>
        [Column("EMAIL", "邮件"), DataSize(64)]
        public string Email
        {
            get
            {
                return this.GetValue<string>("EMAIL");
            }
            set
            {
                this["EMAIL"] = value;
            }
        }

        /// <summary>
        /// 主页 。
        /// </summary>
        [Column("HOMEPAGE", "主页"), DataSize(64)]
        public string Homepage
        {
            get
            {
                return this.GetValue<string>("HOMEPAGE");
            }
            set
            {
                this["HOMEPAGE"] = value;
            }
        }

        /// <summary>
        /// 备注 。
        /// </summary>
        [Column("Remarks", "主页"), DataSize(64)]
        public string Remarks
        {
            get
            {
                return this.GetValue<string>("Remarks");
            }
            set
            {
                this["Remarks"] = value;
            }
        }

        /// <summary>
        /// 数据编码 。
        /// </summary>
        [Column("DataID", "数据编码"), DataSize(10)]
        public int DataID
        {
            get
            {
                return this.GetValue<int>("DataID");
            }
            set
            {
                this["DataID"] = value;
            }
        }

        /// <summary>
        /// 属性模块 。
        /// </summary>
        [Column("MODULE", "属性模块"), DataSize(64)]
        public string Module
        {
            get
            {
                return this.GetValue<string>("MODULE");
            }
            set
            {
                this["MODULE"] = value;
            }
        }

        /// <summary>
        /// 说明 。
        /// </summary>
        [Column("DESCRIPTION", "说明"), DataSize(128)]
        public string Explain
        {
            get
            {
                return this.GetValue<string>("DESCRIPTION");
            }
            set
            {
                this["DESCRIPTION"] = value;
            }
        }

        #endregion
    }
}
