#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET应用开发平台是一套免费的快速开发工具，可以不受限制的用于各种商业开发之中，开发人员可以参考官方网站和博客园
//等专业网站获取公开的技术资料，也可以向AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace EAS.BPM.Entities
{
   /// <summary>
   /// 实体对象 WFDefine(流程定义信息)。
   /// </summary>
   [Serializable()]
   [Table("WF_Define","流程定义信息")]
   partial class WFDefine: DataEntity<WFDefine>
   {
       public WFDefine()
       {
       }
       
       protected WFDefine(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 流程ID 。
       /// </summary>
       [Column("FlowID","流程ID"),DataSize(36),PrimaryKey]
       public string FlowID
       {
           get;
           set;
       }

       /// <summary>
       /// 名称 。
       /// </summary>
       [Column("Name","名称"),DataSize(150)]
       public string Name
       {
           get;
           set;
       }

       /// <summary>
       /// 版本号 。
       /// </summary>
       [Column("VERSION", "版本号")]
       public int Version
       {
           get;
           set;
       }

       /// <summary>
       /// 说明 。
       /// </summary>
       [Column("Desctiption","说明"),DataSize(150)]
       public string Desctiption
       {
           get;
           set;
       }

       /// <summary>
       /// 创建者 。
       /// </summary>
       [Column("Creator","创建者"),DataSize(50)]
       public string Creator
       {
           get;
           set;
       }

       /// <summary>
       /// 创建时间 。
       /// </summary>
       [Column("FCTime","创建时间"),DataSize(23,3)]
       public DateTime FCTime
       {
           get;
           set;
       }

       /// <summary>
       /// 修改者 。
       /// </summary>
       [Column("Modifier","修改者"),DataSize(50)]
       public string Modifier
       {
           get;
           set;
       }

       /// <summary>
       /// 修改时间 。
       /// </summary>
       [Column("LMTime","修改时间"),DataSize(23,3)]
       public DateTime LMTime
       {
           get;
           set;
       }

       /// <summary>
       /// 开始时间 。
       /// </summary>
       [Column("StartTime","开始时间"),DataSize(23,3)]
       public DateTime StartTime
       {
           get;
           set;
       }

       /// <summary>
       /// 结束时间 。
       /// </summary>
       [Column("EndTime","结束时间"),DataSize(23,3)]
       public DateTime EndTime
       {
           get;
           set;
       }

       /// <summary>
       /// 初始状态 。
       /// </summary>
       [Column("InitialState","初始状态"),DataSize(64)]
       public string InitialState
       {
           get;
           set;
       }

       /// <summary>
       /// 完成状态 。
       /// </summary>
       [Column("CompletedState","完成状态"),DataSize(64)]
       public string CompletedState
       {
           get;
           set;
       }

       /// <summary>
       /// 流程定义 。
       /// </summary>
       [Column("Xoml","流程定义")]
       public string Xoml
       {
           get;
           set;
       }

       /// <summary>
       /// 流程规则 。
       /// </summary>
       [Column("Rules","流程规则")]
       public string Rules
       {
           get;
           set;
       }

       /// <summary>
       /// 流程布局 。
       /// </summary>
       [Column("Layout","流程布局")]
       public string Layout
       {
           get;
           set;
       }

       /// <summary>
       /// 流程变量 。
       /// </summary>
       [Column("Variables","流程变量")]
       public string Variables
       {
           get;
           set;
       }

       /// <summary>
       /// 组件名称 。
       /// </summary>
       [Column("Module", "组件名称"), DataSize(150)]
       public string Module
       {
           get;
           set;
       }

       /// <summary>
       /// 组件类型 。
       /// </summary>
       [Column("MType", "组件类型"), DataSize(150)]
       public string MType
       {
           get;
           set;
       }

       /// <summary>
       /// 组件名称/Silverlight 。
       /// </summary>
       [Column("SilverModule", "组件名称/Silverlight"), DataSize(150)]
       public string SilverModule
       {
           get;
           set;
       }

       /// <summary>
       /// 组件类型 /Silverlight 。
       /// </summary>
       [Column("SilverMType", "组件类型 /Silverlight"), DataSize(150)]
       public string SilverMType
       {
           get;
           set;
       }

       /// <summary>
       /// 组件类型 。
       /// </summary>
       [Column("DataType","组件类型"),DataSize(150)]
       public string DataType
       {
           get;
           set;
       }

       /// <summary>
       /// 是否禁用 。
       /// </summary>
       [Column("IsEnable", "状态"), DataSize(10)]
       public int IsEnable
       {
           get;
           set;
       }

       /// <summary>
       /// 状态 。
       /// </summary>
       [Column("IsPublish","状态"),DataSize(10)]
       public int IsPublish
       {
           get;
           set;
       }       

       /// <summary>
       /// 发布人 。
       /// </summary>
       [Column("Publisher","发布人"),DataSize(50)]
       public string Publisher
       {
           get;
           set;
       }

       /// <summary>
       /// 发布日期 。
       /// </summary>
       [Column("PublishTime","发布日期"),DataSize(23,3)]
       public DateTime PublishTime
       {
           get;
           set;
       }
       
       #endregion
   }
}
