#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET应用开发平台是一套免费的快速开发工具，可以不受限制的用于各种商业开发之中，开发人员可以参考官方网站和博客园
//等专业网站获取公开的技术资料，也可以向AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace EAS.BPM.Entities
{
   /// <summary>
   /// 实体对象 WFInstance(流程实例信息)。
   /// </summary>
   [Serializable()]
   [Table("WF_Instance","流程实例信息")]
   partial class WFInstance: DataEntity<WFInstance>
   {
       public WFInstance()
       {
       }
       
       protected WFInstance(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 实例ID 。
       /// </summary>
       [Column("ID","实例ID"),DataSize(36),PrimaryKey]
       public string ID
       {
           get;
           set;
       }

       /// <summary>
       /// 工作流ID 。
       /// </summary>
       [Column("FlowID","工作流ID"),DataSize(36)]
       public string FlowID
       {
           get;
           set;
       }

       /// <summary>
       /// 工作流名称 。
       /// </summary>
       [Column("FlowName", "工作流名称")]
       public string FlowName
       {
           get;
           set;
       }             

       /// <summary>
       /// 标题 。
       /// </summary>
       [Column("Subject","标题"),DataSize(128)]
       public string Subject
       {
           get;
           set;
       }

       /// <summary>
       /// 创建日期 。
       /// </summary>
       [Column("CreateTime","创建日期")]
       public DateTime CreateTime
       {
           get;
           set;
       }

       /// <summary>
       /// 操作日期 。
       /// </summary>
       [Column("ProcessTime","操作日期")]
       public DateTime ProcessTime
       {
           get;
           set;
       }

       /// <summary>
       /// 完成日期 。
       /// </summary>
       [Column("ComplateTime","完成日期")]
       public DateTime ComplateTime
       {
           get;
           set;
       }

       /// <summary>
       /// 发起人 。
       /// </summary>
       [Column("Sender","发起人"),DataSize(64)]
       public string Sender
       {
           get;
           set;
       }

       /// <summary>
       /// 最后处理者 。
       /// </summary>
       [Column("Handler", "最后处理者"), DataSize(100)]
       public string Handler
       {
           get;
           set;
       }

       /// <summary>
       /// 最后参与者 。
       /// </summary>
       [Column("Handlers", "最后参与者"), DataSize(256)]
       public string Handlers
       {
           get;
           set;
       }

       /// <summary>
       /// 参与者 。
       /// </summary>
       [Column("Partner", "参与者"), DataSize(256)]
       public string Partner
       {
           get;
           set;
       }

       /// <summary>
       /// 数据类型 。
       /// </summary>
       [Column("DataType", "数据类型"), DataSize(128)]
       public string DataType
       {
           get;
           set;
       }

       /// <summary>
       /// 业务数据 。
       /// </summary>
       [Column("DataXML", "业务数据"), DataSize(128)]
       public string DataXML
       {
           get;
           set;
       }

       /// <summary>
       /// 上一状态 。
       /// </summary>
       [Column("PreviousState", "上一状态"), DataSize(32)]
       public string PreviousState
       {
           get;
           set;
       }

       /// <summary>
       /// 流程状态 。
       /// </summary>
       [Column("CurrentState", "流程状态"), DataSize(32)]
       public string CurrentState
       {
           get;
           set;
       }

       /// <summary>
       /// 当前状态ID 。
       /// </summary>
       [Column("CSTATEID", "当前状态ID"), DataSize(36)]
       public string CStateID
       {
           get;
           set;
       }

       /// <summary>
       /// 附加权限 。
       /// </summary>
       [Column("ADDLIMIT", "附加权限")]
       public int AddLimit
       {
           get;
           set;
       }

       /// <summary>
       /// 是否完成 。
       /// </summary>
       [Column("IsComplate","是否完成")]
       public int IsComplate
       {
           get;
           set;
       }

       /// <summary>
       /// 错误 。
       /// </summary>
       [Column("Error", "错误"), DataSize(256)]
       public string Error
       {
           get;
           set;
       }

       /// <summary>
       /// 备注 。
       /// </summary>
       [Column("Note","备注"),DataSize(512)]
       public string Note
       {
           get;
           set;
       }
       
       #endregion
   }
}
