--模块表
ALTER TABLE dbo.EAS_MODULES ADD MVCURL VARCHAR(256)
ALTER TABLE dbo.EAS_MODULES ADD OPENTARGET VARCHAR(64)
ALTER TABLE dbo.EAS_MODULES ADD CSSICON VARCHAR(256)

--分组表
ALTER TABLE dbo.EAS_GROUPS ADD CSSICON VARCHAR(256)

--账号表
ALTER TABLE dbo.EAS_ACCOUNTS ADD MASTER NVARCHAR(64)  --主账号
ALTER TABLE dbo.EAS_ACCOUNTS ADD LOGINTIME DATETIME NOT NULL DEFAULT GETDATE()  --最后登录时间
ALTER TABLE dbo.EAS_ACCOUNTS ADD LOGINRETRY INT NOT NULL DEFAULT 0  --登录重试次数